version: "3.9"

services:
  service-one:
    container_name: container_one
    image: image_one
    build:
      context: .
      dockerfile: Dockerfile
      target: one
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
  service-two:
    container_name: container_two
    image: image_two
    build:
      context: .
      dockerfile: Dockerfile
      target: two
    stdin_open: true
    tty: true
    network_mode: host
