version: "3.9"

services:
  service-one:
    container_name: server
    image: simple-flask-api-server
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    stdin_open: true
    tty: true
    networks:
      my-network:
        ipv4_address: 10.1.0.100
  service-two:
    container_name: client
    image: simple-flask-api-client
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    stdin_open: true
    tty: true
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
